import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import Header from "~/components/Header";
import Content from "~/components/Content";

const Home: NextPage = (props) => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {sessionData?.user && <Content />}
        {!sessionData && (
          <div className="mockup-window mx-5 my-5 border bg-base-300">
            <div className="flex justify-center bg-base-200 px-4 py-16">
              <div className="mockup-code">
                <pre data-prefix="$">
                  <code>npm i Notejs</code>
                </pre>
                <pre data-prefix=">" className="text-warning">
                  <code>installing...</code>
                </pre>
                <pre data-prefix=">" className="text-success">
                  <code>Done! Your code notes successfully installed</code>
                  <br />
                </pre>
                <pre data-prefix=">">
                  <button
                    className="bg-info px-2 text-black"
                    onClick={() => {
                      void signIn();
                    }}
                  >
                    Signin Here !
                  </button>
                </pre>
              </div>
            </div>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
